[2017-09-21 14:47:28.302] [ERROR] error - { code: 'E1105',
  info: 'uncaught_web_err',
  msg: 'Error: Can\'t set headers after they are sent.\r\n' }
[2017-09-21 14:49:54.516] [ERROR] error - { code: 'E1105',
  info: 'uncaught_web_err',
  msg: 'Error: Can\'t set headers after they are sent.\r\n' }
[2017-09-21 14:51:08.247] [ERROR] error - { code: 'E1105',
  info: 'uncaught_web_err',
  msg: 'Error: Can\'t set headers after they are sent.\r\n' }
[2017-09-21 14:52:47.734] [ERROR] error - { code: 'E1105',
  info: 'uncaught_web_err',
  msg: 'Error: Can\'t set headers after they are sent.\r\n' }
[2017-09-21 15:05:03.452] [ERROR] error - { code: 'E1105',
  info: 'uncaught_web_err',
  msg: 'Error: Can\'t set headers after they are sent.\r\n' }
[2017-09-21 15:11:15.731] [ERROR] error - { code: 'E1105',
  info: 'uncaught_web_err',
  msg: 'Error: Can\'t set headers after they are sent.\r\n' }
[2017-09-21 15:41:03.488] [ERROR] error - { code: 'E1105',
  info: 'uncaught_web_err',
  msg: 'TypeError: Cannot read property \'RowDataPacket\' of undefined\r\n' }
[2017-09-21 15:42:22.866] [ERROR] error - { code: 'E1105',
  info: 'uncaught_web_err',
  msg: 'SyntaxError: Unexpected token u\r\n' }
[2017-09-21 15:44:02.591] [ERROR] error - { code: 'E1105',
  info: 'uncaught_web_err',
  msg: 'SyntaxError: Unexpected token u\r\n' }
[2017-09-21 15:47:18.903] [ERROR] error - { code: 'E1105',
  info: 'uncaught_web_err',
  msg: 'TypeError: Cannot read property \'a\' of undefined\r\n' }
[2017-09-21 15:54:56.885] [ERROR] error - { code: 'E1105',
  info: 'uncaught_web_err',
  msg: 'TypeError: Cannot read property \'stat_mon\' of undefined\r\n' }
[2017-10-10 13:50:58.102] [ERROR] error - { code: 'E1105',
  info: 'uncaught_web_err',
  msg: 'MongoError: connection 0 to 10.201.253.111:27017 timed out\r\n' }
[2017-10-10 13:51:55.470] [ERROR] error - { code: 'E1105',
  info: 'uncaught_web_err',
  msg: 'MongoError: failed to connect to server [127.0.0.1:27017] on first connect\r\n' }
[2018-03-26 12:25:14.252] [ERROR] error - { code: 'checkCode', info: '编码重复', msg: '"p-109"' }
[2018-03-26 12:27:38.794] [ERROR] error - { code: 'checkCode', info: '编码重复', msg: '"p-109"' }
[2018-03-26 12:54:05.063] [ERROR] error - { code: 'checkCode', info: '编码重复', msg: '"p_104"' }
[2018-03-26 12:55:25.847] [ERROR] error - { code: 'checkCode', info: '编码重复', msg: '"p-108"' }
[2018-04-12 13:25:56.601] [ERROR] error - { code: 'getProcessDefineByConditionMap',
  info: '获取流程定义信息时出现异常',
  msg: '{"name":"MongoError","message":"connection 14 to 192.168.9.48:27017 timed out"}' }
[2018-04-12 13:25:56.618] [ERROR] error - { code: 'getProcessDefineByConditionMap',
  info: '获取流程定义信息时出现异常',
  msg: '{"name":"MongoError","message":"connection 14 to 192.168.9.48:27017 timed out"}' }
[2018-04-12 13:25:56.623] [ERROR] error - { code: 'getProcessDefineByConditionMap',
  info: '获取流程定义信息时出现异常',
  msg: '{"name":"MongoError","message":"connection 27 to 192.168.9.48:27017 timed out"}' }
[2018-04-12 13:25:56.624] [ERROR] error - { code: 'getProcessDefineByConditionMap',
  info: '获取流程定义信息时出现异常',
  msg: '{"name":"MongoError","message":"connection 27 to 192.168.9.48:27017 timed out"}' }
[2018-04-12 13:25:56.624] [ERROR] error - { code: 'getProcessDefineByConditionMap',
  info: '获取流程定义信息时出现异常',
  msg: '{"name":"MongoError","message":"connection 1 to 192.168.9.48:27017 timed out"}' }
[2018-04-12 13:25:56.624] [ERROR] error - { code: 'getProcessDefineByConditionMap',
  info: '获取流程定义信息时出现异常',
  msg: '{"name":"MongoError","message":"connection 1 to 192.168.9.48:27017 timed out"}' }
[2018-04-12 13:25:56.624] [ERROR] error - { code: 'getProcessDefineByConditionMap',
  info: '获取流程定义信息时出现异常',
  msg: '{"name":"MongoError","message":"connection 12 to 192.168.9.48:27017 timed out"}' }
[2018-04-12 13:25:56.625] [ERROR] error - { code: 'getProcessDefineByConditionMap',
  info: '获取流程定义信息时出现异常',
  msg: '{"name":"MongoError","message":"connection 21 to 192.168.9.48:27017 timed out"}' }
[2018-04-12 13:25:56.625] [ERROR] error - { code: 'getProcessDefineByConditionMap',
  info: '获取流程定义信息时出现异常',
  msg: '{"name":"MongoError","message":"connection 11 to 192.168.9.48:27017 timed out"}' }
[2018-04-12 13:25:56.625] [ERROR] error - { code: 'getProcessDefineByConditionMap',
  info: '获取流程定义信息时出现异常',
  msg: '{"name":"MongoError","message":"connection 9 to 192.168.9.48:27017 timed out"}' }
[2018-04-12 13:25:56.625] [ERROR] error - { code: 'getProcessDefineByConditionMap',
  info: '获取流程定义信息时出现异常',
  msg: '{"name":"MongoError","message":"connection 16 to 192.168.9.48:27017 timed out"}' }
[2018-04-12 13:25:56.625] [ERROR] error - { code: 'getProcessDefineByConditionMap',
  info: '获取流程定义信息时出现异常',
  msg: '{"name":"MongoError","message":"connection 16 to 192.168.9.48:27017 timed out"}' }
[2018-04-12 13:25:56.625] [ERROR] error - { code: 'getProcessDefineByConditionMap',
  info: '获取流程定义信息时出现异常',
  msg: '{"name":"MongoError","message":"connection 16 to 192.168.9.48:27017 timed out"}' }
